export const GET_BRANCHES_LOADING = "GET_BRANCHES_LOADING";
export const GET_BRANCHES_SUCCESS = "GET_BRANCHES_SUCCESS";
export const GET_BRANCHES_FAILED = "GET_BRANCHES_FAILED";

export const GET_SERVING_BRANCHES_LOADING = "GET_SERVING_BRANCHES_LOADING";
export const GET_SERVING_BRANCHES_SUCCESS = "GET_SERVING_BRANCHES_SUCCESS";
export const GET_SERVING_BRANCHES_FAILED = "GET_SERVING_BRANCHES_FAILED";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const GET_USER_LOADING = "GET_USER_LOADING";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const NOTIFICATION_RECEIVED = "NOTIFICATION_RECEIVED";

export const LOGOUT = "LOGOUT";
